package common


const (

	STATUS_ERROR = 100

	STATUS_OK = 200

	REQUEST_PARAMETER_ERROR = 1010
	REQUEST_PARAMETER_BIND_ERROR = 1011
	REQUEST_PARAMETER_VALID_ERROR = 1012

	REQUEST_NOT_HAS_HEADER = 1013

	//用户
	USER_NOT_LOGIN = 2010
	USER_LOGIN_FIALD = 2011
	USER_NOT_PERMISSION = 2020

	//token
	TOKEN_NOT_EXISTS = 1020
	TOKEN_VALIDATION_FAILED = 1021
)

var StatusMsg = map[int]string{
	STATUS_ERROR: "Other Error",

	STATUS_OK: "OK",

	USER_NOT_LOGIN: "Not Login",

	USER_NOT_PERMISSION: "Not Have Permission",
}
